#ifndef WORKFLOW_ENGINE_INCLUDE_WORKFLOW_ENGINE_UTILITY_LOGGER_H
#define WORKFLOW_ENGINE_INCLUDE_WORKFLOW_ENGINE_UTILITY_LOGGER_H

#include <string>
#include <memory>

namespace we
{

}

#endif //WORKFLOW_ENGINE_INCLUDE_WORKFLOW_ENGINE_UTILITY_LOGGER_H
